site_name: 韩昌黎文集
nav:
  - 简介: index.md
  - 大唐凝思: 文/大唐凝思.md
  - 原道: 文/原道.md
  - 进学解: 文/进学解.md

theme: readthedocs

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']
