site_name: 韩昌黎文集
nav:
  - 大唐凝思: 文/大唐凝思.md
  - 原道: 文/原道.md
  - 进学解: 文/进学解.md
  - 送李愿归盘古序: 文/送李愿归盘古序.md
  - 送孟东野序: 文/送孟东野序.md
  - 原毁: 文/原毁.md

theme: readthedocs

extra_javascript: ['https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML','js/mathjaxhelper.js']
